# Generated by Django 3.0.5 on 2020-05-02 12:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200429_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drowsydriveruser',
            name='photo',
        ),
        migrations.AddField(
            model_name='drowsydriveruser',
            name='next_of_kin_name',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='drowsydriveruser',
            name='next_of_kin_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
