# Generated by Django 3.0.5 on 2020-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200502_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drowsydriveruser',
            name='next_of_kin_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
