# Generated by Django 3.0.5 on 2020-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='car_registration_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
