# Generated by Django 3.0.5 on 2020-06-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_stats', '0002_stats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(default=969, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
