# Generated by Django 3.0.5 on 2020-05-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_stats', '0003_auto_20200519_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='user',
        ),
        migrations.AddField(
            model_name='stats',
            name='drowsydriveruser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
