# Generated by Django 3.0.5 on 2020-05-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_stats', '0004_auto_20200520_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='drowsydriveruser',
        ),
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stats',
            name='eye_aspect_ratio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='time_alarm_raised',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
